#ifndef ZNMCONTROLBASE_GLOBAL_H
#define ZNMCONTROLBASE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ZNMCONTROLBASE_LIBRARY)
#  define ZNMCONTROLBASESHARED_EXPORT Q_DECL_EXPORT
#else
#  define ZNMCONTROLBASESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ZNMCONTROLBASE_GLOBAL_H
